import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
    title: {
        default: "NET App",
        template: "%s | NET App"
    },
    description: "Generated by create next app"
};

const ToastifyNoSSR = dynamic(() => import("../components/Toastify/Toastify"), { ssr: false });

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className="flex h-screen w-full items-center justify-center overflow-hidden bg-gray-100">
                <ToastifyNoSSR />
                {children}
            </body>
        </html>
    );
}
