import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "NET App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className="flex h-screen w-full items-center justify-center overflow-hidden bg-gray-100">{children}</body>
        </html>
    );
}
